### ISSUE TITLE
Impossible to select vertices trough GIZMO

### ISSUE THREAD

**Issue by AUTUMNIIIWIND** [AIGODLIKE/PlaceHelper#5]
Hi,

Firstly, I want to say that I enjoy your add-on a lot.
All tools are great, but the best it EXTRUDE with SHIFT.

I noticed 2 problems.

PROBLEM 1
-----------------
It is impossible to select vertices trough TRANSFORM PRO GIZMO
When VERTEX is behind the TRANSFORM PRO GIZMO ARROW, and you are trying to click it, it is very hard to do it.
You have to rotate the model to the point where the VERTEX you want to select is away from the TRANSFORM PRO GIZOMO.

MOVE TOOL in Blender ignores 1x CLICK, so it is easy to select. 

MAYBE IT'S BECAUSE BLENDER "MOVE GIZMO" IS A LITTLE BIT TRANSPARENT?

Would be nice if you could add the same behavior, because I want to replace MOVE TOOL with your TRANSFORM PRO GIZMO, but the selection problem is very annoying.

PROBLEM 2
-----------------

Sometimes TRANSFORM PRO GIZMO disappears for no reason.
When this happens, the only way to fix it is to restart Blender.
But I noticed this also with another tool, which is EXTRUDE ALONG NORMALS.

I wonder, maybe you know why is this happening?

Anyway, thank you for a great add-on!

**Comment by Yorha4D** [comment]
@AUTUMNIIIWIND Regarding Question 1
The current GIZMO setting at the front does indeed obscure the selection of other elements. Let me take a look at this issue (you can try sliding the perspective to reduce occlusion first)
Regarding Question 2
What is your Blender version? There is a malfunction in the official code of several special Blender versions, causing Gizmo to malfunction

**Comment by AUTUMNIIIWIND** [comment]
Hi, thank you for response.
That would be great if you could make possible to select through the GIZMO.
I noticed that Blender MOVE gizmo is a little bit transparent, I do not have a clue if this is related to the selection problem with your GIZMO. But your GIZMO is not transparent, so maybe it is.

I use Blender 4.3.2 portable ver.
All of my add-ons are located in the "portable" folder inside the Blender root folder.
It is rather very clean build with latest add-ons.

Thank you for your effort!

**Comment by AUTUMNIIIWIND** [comment]
I noticed another problem.

It's impossible to move/push the FACE when TRANSFORM ORIENTATION is set to NORMAL.

**Comment by xmx-emm** [comment]
resolved
https://github.com/AIGODLIKE/PlaceHelper/releases/tag/v1.3.3

**Comment by AUTUMNIIIWIND** [comment]
Thanks for the update!

Unfortunately it doesn't work. I noticed that you added transparency. But if I try to select EDGE or VERTEX, GIZMO still blocks the selection.

And now I wonder if maybe you misunderstood me. It's great that you added transparency for GIZMO, unfortunately the main problem with GIZMO blocking the selection still exists.

Compare how selecting VERTEX looks like when it is covered by GIZMO MOVE the one that Blender has.
And compare it to your GIZMO "PlaceHelper".

I tried setting the transparency to 0.1, unfortunately that doesn't help either. I noticed that when I hover the cursor over GIZMO's "PlaceHelper", it turns white and is no longer transparent.

Maybe that's the problem?

As for the problem **"It's impossible to move/push the FACE when TRANSFORM ORIENTATION is set to NORMAL."**

On the first test everything seemed OK.

But I need more time to make sure.

Anyway, thank you for trying to fix this!

**Comment by xmx-emm** [comment]
I see what you mean, the code is a bit of a mess right now and I need a bit of time to refactor it

**Comment by AUTUMNIIIWIND** [comment]
Thank you so much!
Take your time.

**Comment by xmx-emm** [comment]
already achieved
https://github.com/AIGODLIKE/PlaceHelper/releases/tag/v1.3.4

**Comment by AUTUMNIIIWIND** [comment]
Hi, first of all thank you very much for fixing problem with selection so quickly!

I tested GIZMO for about 2 hours. And I have a few suggestions. 
I don't want it to sound like I'm demanding anything from you. 
These are just my suggestions that I think will improve your GIZMO and make working with it more enjoyable.

I'll start with a comparison with the original GIZMO MOVE from Blender.
Generally, it would be best if there was an option to apply all the settings of this MOVE GIZMO from Blender to your GIZMO.
I mean all the distances of the manipulators, and the size of the circle in the center of the GIZMO to be exactly the same

SUGGESTION 1

I think that the circle in the center of your GIZMO, is too big. At least much bigger than the one that Blender has. 
Because of that it is very often in the way of the VERTEX that I want to select.
When I was working for two hours, I noticed that very often I move the VERTEX, when I wanted only to select VERTEX. 
Feels that reaction for MOVING it's faster than reaction for SELECTION. So instead of SELECTING another vertex, I MOVE the one already selected.

When I make my selection slowly, everything works as it should, unfortunately I work quite fast and it affects my precision.
The scale/diameter of the CIRCLE in the center of the GIZMO from Blender is smaller, because of this, when you are selecting a VERTEX, it very rare to make already selected VERTEX move.

I see two solutions:

1. Add a preset that will allow you to make the circle in the middle of the GIZMO smaller (The same size as Blender MOVE GIZMO). 
2. Or a setting that allows change the scale of the center circle. I think that would be interesting if you could make this circle very large, so it is larger than all the Axis arrows. Or very small, so smaller than original Blender MOVE GIZMO.

SUGGEST 2

GIZMO MOVE in Blender, when you set the GIZMO arrow to point straight at YOU/CAMERA, the arrow disappears, revealing the work area.

It is not very inconvenient, but it would be nice if such functionality appeared in your GIZMO.

SUGGEST 3

This is more of a request than a suggestion.
I have noticed that the GIZMO highlighting in white is very distracting for me. 
When there are many VERTICES nearby, and I move the cursor quite quickly. The circle in the middle of GIZMO and the Axis arrows are flickering, and distracting me. 
Like I already said, I move the cursor pretty fast, and my focus needs to stay only on my next sekection. And when everything is blinking, I lost my target.
I hope that it does not sound silly, I'm just honest, trying to explain my feelings the best possible way.

It would be nice if you could add the ability to set transparency when you hover the mouse over GIZMO's manipulators. Similar to GIZMO ALPHA that already implemented.
This way it would be possible to make hover color change very subtle so not distracting.


I hope that you will find my suggestions worth implementing.
Ones again, thank you so much for this update, this is a great improvement!

PS.
My english is not that great, so if you are confused with something I said please ask. I will try to make better description.

**Comment by xmx-emm** [comment]
Perhaps a new issue should be created

1.Will add the preference GIZMO centre circle size setting, and the default is the same as the blender size.

2.Don't quite get it I compared it and there is no noticeable difference in view mode

3.Will modify colour_highlight

I use machine translation too. Don't worry about it

**Comment by xmx-emm** [comment]
haven't found a better way of not displaying the axis at the centre circle position yet, so still display the axis here
![Image](https://github.com/user-attachments/assets/da8752d3-d453-4183-8351-f2a176f19a4d)

![Image](https://github.com/user-attachments/assets/e1a72579-0027-4d2d-b338-affc8dd7c4b6)

**Comment by AUTUMNIIIWIND** [comment]
Hi, it does look great!

But I think that you do not have to change the AXIS, they can merge in the center, this is just fine. 
I think that it's even better looking if they are merged in the center, does look better this way, and this is not the problem at all.
**But maybe I'm wrong, and this can affect the VERTEX selection!**
If you can keep both settings, then I could test it, and tell you how I feel about it.
Right now It is hard to tell, I need to test it first.

The main problem is the fast selection. 
I created video, so you can see what I mean.
You can notice that when I select the VERTEX slowly, it will work just fine, but when I'm doing it fast it's not.

For now, I just use two GIZMO's, the MOVE from Blender and yours, and I could live with this.
But I want to use only your GIZMO for all tasks. 
EDGE EXTRUDE feature is so great, and I love this feature, this is why I want your GIZMO to be perfect.

Anyway, check the video.

https://github.com/user-attachments/assets/d93bdaad-7efc-46fc-b9d0-7de937ab59b2

Do you know **Gizmo PRO** add-on?
The best GIZMO configuration I can think about is the one from **Gizmo PRO**
There are so many settings, you can make nearly everything with it, color change, size change, position change, it's very well-designed.

Sadly this add-on was not updated for a very long time, and from what I know is not working well, in Blender 4.3
But it can be an inspiration for you, because the configuration possibilities are amazing, you can do so much with the GIZMO in this add-on.

https://derksen.gumroad.com/l/gizmopro

I created another video to show you how the original GIZMO disappears when the arrow point at the camera.
But like I said, this i not a big deal, but would be great if you could add this feature.

Anyway, I can't wait to test the new update.
I'm very grateful that you are listening to my feedback, thank you so much!

https://github.com/user-attachments/assets/46489f62-2f3f-46d7-bbee-85a460995624

**Comment by AUTUMNIIIWIND** [comment]
Oh, I did not understand what you said, and I had to read it again...
I was thinking that you showed on the pictures updated GIZMO.
But you wanted to show me the size comparison, and show me that you can't see any difference.

I did not notice that you showed both GIZMO's, the one from Blender, and yours.
I'm sorry!

Please look at my videos.
You will see clearly that sizes are different.

Maybe you use a different Blender build than me, and maybe this is the problem?

I use portable **Blender 4.3.2**

**Comment by xmx-emm** [comment]
Choices can be optimised
Alpha will not be modified, Too much work

Maybe you can test the gizmo to see if there are any improvements that can be made.
[zip](https://codeload.github.com/AIGODLIKE/PlaceHelper/zip/refs/heads/develop)

A new version will be released next week

**Comment by AUTUMNIIIWIND** [comment]
I can't see any difference.
The selection problem is still there, it is impossible to select fast the same way as with MOVE Blender GIZMO.

And the white CIRCLE, in the center, is still way bigger than MOVE Blender GIZMO.

**When I'm moving the cursor on the video, and nothing is changing, I'm clicking too, I'm trying to select the other vertex, but as you can see I have hard time to make my selection when clicking fast**

Maybe you send me wrong file?

https://github.com/user-attachments/assets/003207bc-c972-416a-9ad1-5c870d4b9d6f

**Comment by xmx-emm** [comment]
Try this out [PlaceHelper-develop.zip](https://github.com/user-attachments/files/19155836/PlaceHelper-develop.zip)
Quick selection should no longer be a problem

The size of the gizmo is very strange
It seems that the display size on each computer is not fixed
Resolution scaling may affect

**Comment by AUTUMNIIIWIND** [comment]
Hi, I tested for 1,5 hour, and so far, FAST VERTEX selection works great!
You did possible to change the size of the center circle too, and this is super cool!
Possibility to change size of the center circle is very good because it helps to work with your GIZMO.

And now I will try to explain why, and what I noticed when working with your GIZMO.

So original Blender MOVE GIZMO, works like this.
CENTER CIRCLE AREA, is responsible for moving the GIZMO, this way I do not have to select only the CIRCLE RIM.
I can click just inside the CIRCLE AREA, and it will be possible to MOVE THE GIZMO.
Also, what important, is that ALL AXIS ARROWS, are outside the CENTER CIRCLE AREA, this way it's impossible to select them by accident, and move the GIZMO in wrong direction.

Also, AND THIS IS VERY IMPORTANT!
Cursor right after you select CENTER CIRCLE AREA, will stay nearly in the place where you click LEFT MOUSE BUTTON.
This is why it is possible to make rapid moves with the mouse, and still have GIZMO just next to the cursor.

I will show 2 example VIDEO, in the first one I will show you ORIGINAL BLENDER MOVE GIZMO.
And then I will show you your GIZMO.

VIDEO 1 - ORIGINAL BLENDER MOVE GIZMO.

https://github.com/user-attachments/assets/6759a609-f558-4926-a775-8775a0b17606


As you can see, I can be very fast and precise with my movement, and the cursor will stay close to the GIZMO, even if my mouse moves are very rapid.

-------------------------------------------------------------------------

Now I will try to explain how your GIZMO works.
The CENTER CIRCLE AREA is not selectable, inside the CIRCLE AREA, Blender thinks that you are clicking any outside area of the viewport.
Inner CENTER CIRCLE AREA is not selectable.
When I move the mouse cursor inside the CENTER CIRCLE, (THE AREA INSIDE THE RIM), the first "ITEM" MOUSE CURSOR will touch will be activated.
So when it touches one of the AXIS you will move AXIS ARROW instead.

Another thing is a RAPID MOVES, even if I will click at the CIRCLE RIM, but I will move my cursor fast, the distance between the GIZMO, and MOUSE CURSOR will change.
Because of this, rapid mouse moves are rather hard to execute with TRANSFORM PRO.
The distance between the GIZMO and CURSOR it's pretty big.

VIDEO 2 - TRANSFORM PRO

https://github.com/user-attachments/assets/9ea2ba14-485c-46b6-aad5-883e82128653

-------------------------------------------------------------------------

My opinion.

I still can't be fast enough working with the TRANSFORM PRO GIZMO.
To make the precision better, I changed CENTER CIRCLE size to 1.5, this way I do not touch the AXIS ARROWS by accident anymore, and this way all works just fine.

![Image](https://github.com/user-attachments/assets/08a7981f-33d6-4aff-a802-6fa92cd8413f)

I think that TRANSFORM PRO is just fine, when you work with average speed, chilling while modeling. 
Sadly, for fast modeling I will still use BLENDER ORIGINAL MOVE GIZMO.

I think that you did already great job!
FAST VERTEX SELECTION, GIZMO ALPHA, and adjustable CENTER CIRCLE makes a huge difference!

**I COULD NOT BELIEVE HOW MANY PROBLEMS YOU HAVE TO WORK WITH WHILE DEVELOPING THE GIZMO, THIS IS PRETTY COMPLEX TASK.**

Anyway, thank you so much for your work, and if you will decide to improve it in the future, I will be happy to make more tests.

**Comment by xmx-emm** [comment]
Try this.
I added some controllable properties in the preferences
You might like it.

[PlaceHelper-develop_2.zip](https://github.com/user-attachments/files/19174990/PlaceHelper-develop_2.zip)

![Image](https://github.com/user-attachments/assets/f7e1bd6c-4b84-4d7c-b29c-c65be9487d4e)

![Image](https://github.com/user-attachments/assets/dd77d4bb-72a4-43e6-8d24-5d6503ead8e6)

Blender's centre circle is the entire area that can be moved, haven't found a way to do the same yet, let me try!

**Comment by xmx-emm** [comment]
I added the alpha change by view

[PlaceHelper-develop_3.zip](https://github.com/user-attachments/files/19175913/PlaceHelper-develop_3.zip)

https://github.com/user-attachments/assets/15d07054-0c5d-425b-93a7-f56043876386

**Comment by AUTUMNIIIWIND** [comment]
WOW, you are doing a great job!
This update is fantastic!

I love MOVE EVENT COUNT, makes the GIZMO very precise!

----------------------------------------------

My settings:

![Image](https://github.com/user-attachments/assets/7b1ca75e-0130-46b1-a4eb-66e317bdc4c9)

**CIRCLE SIZE**

I have to make smaller, the sweet spot is 0.15, this way I rather never missed the gizmo, I need to work a little bit more with it to be sure, but so far 0.15 is the best for me.

When is set to default 0.20 I missed gizmo.
It is because the size of the Blender cursor (is not big enough) and because of this, it is impossible to have contact with CENTER CIRCLE all the time.

**ARROW OFFSET**

Because I move Blender CURSOR fast, and I'm chaotic, I prefer to move the AXIS arrows away from CENTER CIRCLE. 

0.35 is my setting.

This way, do not touch the AXIS arrows by mistake trying to select CENTER CIRCLE, and it works.

**ARROW LENGTH**

0.40 feels great

**MOVE EVENT COUNT**

I set it to 1, it's the best this way!

https://github.com/user-attachments/assets/0a12538b-0bec-470c-a146-d3e9561bbbeb

--------------------------------------------------------------------

**MY SUGGESTIONS:**

1. If you do not find a solution for CENTER CIRCLE ENTIRE AREA selection, you should change the size of the CENTER CIRCLE to 0.15 for a final release.


2. Would be great if AXIS ARROW could disappear completely when is pointing straight at YOU/CAMERA. 
In this position, AXIS ARROW is not needed at all, just blocking the selection and the view.

**EDIT:** 
I did not notice that you made video with this feature!
I do not know why, but it does not work for me!


3. Would be nice if 2 AXIS SQUARED manipulators could disappear when moving the GIZMO (not necessary, but would be nice to have it)


**INSANE SUGGESTIONS:**

1. You could add settings to change the thickness of the AXIS ARROWS and THE STICK, 
So you could change the size of the AXIS ARROW, and THE STICK separately.

2. Would be cool to disable visibility of the ARROW at the end of the AXIS manipulator, so only THE STICK is visible.

--------------------------------------------------------------------

**I FOUND A BUG**

When I was playing with the size of the CENTER CIRCLE, for most of the time I was using the size 0.15

But at the end I changed the size back to 0.20, and then it happens.

When I wanted to move VERTX FAST, or select vertex fast, it’s hard to tell when this happens.
GIZMO get broken moved away from selected VERTEX.

The FIX is very easy!
You just have to select VERTEX AGAIN.
It happens only when CENTER CIRCLE size was set to 0.20

But I did not test long enough to be sure that it will happen only when size is set to 0.20


https://github.com/user-attachments/assets/183d0a9a-3c19-426a-a926-2bab086227ee

https://github.com/user-attachments/assets/553c2a53-f0be-4391-9272-2bed348de041

**Comment by AUTUMNIIIWIND** [comment]
OK, I know why I did not notice AXIS ARROWS VISIBILITY change.

Because AXIS will sometimes disappear, sometimes not. 

I think it can be related to the ARROW OFFSET, and ARROW LENGTH settings.

For example, on this video, RED AXIS does not disappear.

https://github.com/user-attachments/assets/a0853d2b-f693-4862-938e-e6bacb28e17f

**Comment by xmx-emm** [comment]
I need to spend some time modifying it

It's strange that the same parameters display differently on different computers
need to know your window scaling factor to see if it's different

Angle alpha requires more time for debugging，I will put this feature in a later version

It seems that if two 3D area appear, there will be issues with updating Gizmo

**Comment by nurb2kea** [comment]
@xmx-emm  Just for INFO !
Hi, while reading your last comment, MacOS comes to my mind.
On macOS we also have the scaling with the 5K Studio and Retina Displays...
So when solving the scaling issues, it would be good to look after the apple ones as well.
I'm on latest MacOS + blender silicon 4.3 / 4.4 / 4.5 and haven't seen an issue with the last official version!!

**Comment by xmx-emm** [comment]
@nurb2kea Sorry, this may not be possible
Because I don't have a Mac device available for debugging
It is difficult to achieve consistency in compatibility with all devices
﻿
Sometimes the code I write runs smoothly on my computer without any issues
But there will be many strange bugs on other people's computers   :>

**Comment by nurb2kea** [comment]
I know and understand.
You can use a free Virtual Machine to run MacOS & Linux to support those if you want.
For the testing, I do it anyways when working...
Also those scaling issues are mostly gone when fixed once. The same issue was with boxcutter and hardops.
Took them some tries, but now I haven't seen any issue at all since it was fixed.
Maybe have a chat with masterxeon1001 about this. He can give you ideas or hints on how to solve.

**Comment by xmx-emm** [comment]
I don't have any more development power at the moment. I am currently maintaining multiple addons

**Comment by AUTUMNIIIWIND** [comment]
Hi, I use Windows 11, scaling 100%, resolution 2560x1440.
Take your time, and good luck trying to fix it!

**Comment by xmx-emm** [comment]
transform tool add alpha vary

https://github.com/AIGODLIKE/PlaceHelper/releases/tag/v1.3.6

If there are any other questions, open a new issues
